import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>e-commerce Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to e-commerce Project Subpage
        </h1>

        <div className={styles.description}>
         <ul>
         <li><Link href="/">Link to e-commerce project root page</Link></li>
         <li><Link href="/spring-summer-2023-fashion-show/subpage">Link to brand-platform project sub page</Link></li>
         </ul>
        </div>
      </main>
    </div>
  )
}
